name: Build

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: execute build
        run: python build.py

      - name: commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Github"
          git add nf version -f
          git diff-index --quiet HEAD || (git commit -a -m "built nf" --allow-empty)

      - name: push
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}}
          branch: dev
