name: Build

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: execute build
        run: python build.py
        
      - name: PyInstaller (Windows)
  # You may pin to the exact commit or the version.
  # uses: JackMcKew/pyinstaller-action-windows@a8dee21ad01bbc7e7363d445bb632691b95ba057
        uses: JackMcKew/pyinstaller-action-windows@v0.1.2
        with:
          path: .
          spec: nf.spec

      - name: PyInstaller (Linux)
  # You may pin to the exact commit or the version.
  # uses: JackMcKew/pyinstaller-action-windows@a8dee21ad01bbc7e7363d445bb632691b95ba057
        uses: JackMcKew/pyinstaller-action-linux@0.1.4
        with:
          path: .
          spec: nf.spec

      - name: commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Github"
          git add -f nf dist/windows/nf.exe dist/linux/nf
          git diff-index --quiet HEAD || (git commit -a -m "Built nf `cat version`" --allow-empty)
      - name: push
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}}
          branch: dev
